apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-api-config
  namespace: wallet
data:
  SPRING_PROFILES_ACTIVE: docker
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet_db
  SPRING_DATASOURCE_USERNAME: wallet_user
  SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://localhost:8081/realms/wallet-realm/protocol/openid-connect/certs
---
apiVersion: v1
kind: Secret
metadata:
  name: wallet-api-secret
  namespace: wallet
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: wallet_password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api
  namespace: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
    spec:
      containers:
        - name: wallet-api
          image: enterprise-wallet-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: wallet-api-config
            - secretRef:
                name: wallet-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-api
  namespace: wallet
spec:
  type: NodePort
  selector:
    app: wallet-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080