apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.heapSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200